services:
  landing:
    image: nginx:alpine
    container_name: dq_landing
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    external: true 
    name: dequa_nw
